'use client';
import React, { useEffect, useMemo, useState } from 'react';

async function api(url, init) {
  const res = await fetch(url, { ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) } });
  const json = await res.json();
  if (!res.ok || json?.success === false) throw new Error(json?.error?.message || 'API error');
  return json.data ?? json;
}

function formatMoney(value, currency = 'VND') {
  return new Intl.NumberFormat('vi-VN', { style: 'currency', currency, maximumFractionDigits: 0 }).format(Number(value || 0));
}
function onlyDate(v) { return v ? String(v).slice(0,10) : ''; }
function parseDate(v) { return new Date(`${onlyDate(v)}T00:00:00`); }
function diffDays(a,b){ return Math.round((b-a)/86400000); }
function addDays(date,days){ const d=new Date(date); d.setDate(d.getDate()+days); return d; }

function Card({children,className=''}) { return <div className={`bg-[#151518] border border-[#26262A] rounded-2xl p-4 shadow-[0_0_20px_rgba(227,29,26,0.08)] ${className}`}>{children}</div>; }
function Btn({children,onClick,secondary,disabled}) { return <button disabled={disabled} onClick={onClick} className={secondary?'rounded-xl border border-[#26262A] bg-[#111114] px-4 py-2 text-[#F5F5F5] hover:bg-[#1A1A1D] disabled:opacity-50':'rounded-xl bg-[#E31D1A] px-4 py-2 text-white hover:bg-[#c71613] disabled:opacity-50'}>{children}</button>; }

function GanttChart({ projects, companies, previewActions, onDropReschedule }) {
  const companyMap = useMemo(() => Object.fromEntries(companies.map(c=>[c.id,c.companyName])), [companies]);
  const previewMap = useMemo(() => Object.fromEntries((previewActions||[]).filter(a=>a.type==='reschedule_project').map(a=>[a.projectId,a])), [previewActions]);
  const [dragging, setDragging] = useState(null);
  const range = useMemo(() => {
    if (!projects.length) { const now = new Date(); return { start: now, end: addDays(now,30)}; }
    const starts = projects.map(p=>parseDate(p.startDate));
    const ends = projects.map(p=>parseDate(p.endDate||p.startDate));
    return { start: addDays(new Date(Math.min(...starts.map(d=>d.getTime()))), -2), end: addDays(new Date(Math.max(...ends.map(d=>d.getTime()))),6)};
  }, [projects]);
  const totalDays = Math.max(1, diffDays(range.start, range.end)+1);
  const days = Array.from({length: totalDays}, (_,i)=>addDays(range.start,i));
  const priorityClass = (p) => p==='urgent'?'from-[#991B1B] to-[#EF4444] border-red-400':p==='high'?'from-[#B45309] to-[#F59E0B] border-amber-400':p==='medium'?'from-[#1D4ED8] to-[#38BDF8] border-sky-400':'from-[#3F3F46] to-[#71717A] border-slate-400';
  function handlePointerUp(e){
    if(!dragging) return;
    const grid=e.currentTarget.getBoundingClientRect();
    const deltaX=e.clientX-dragging.startX;
    const deltaDays=Math.round(deltaX/Math.max(grid.width/totalDays,1));
    const nextStart=addDays(parseDate(dragging.startDate),deltaDays); const nextEnd=addDays(parseDate(dragging.endDate),deltaDays);
    setDragging(null);
    onDropReschedule(dragging.projectId, onlyDate(nextStart.toISOString()), onlyDate(nextEnd.toISOString()));
  }
  return <div className="overflow-auto rounded-2xl border border-[#26262A] bg-[#101013]"><div className="min-w-[1100px]"><div className="grid" style={{gridTemplateColumns:`260px repeat(${totalDays}, minmax(28px,1fr))`}}><div className="border-b border-r border-[#26262A] bg-[#151518] px-4 py-3 text-sm font-semibold">Dự án</div>{days.map(day=><div key={day.toISOString()} className="border-b border-r border-[#1F1F24] px-1 py-3 text-center text-[10px] text-[#9CA3AF]">{String(day.getDate()).padStart(2,'0')}</div>)}</div><div onPointerUp={handlePointerUp}>{projects.map(project=>{const cs=onlyDate(project.startDate), ce=onlyDate(project.endDate||project.startDate); const off=diffDays(range.start, parseDate(cs)); const width=Math.max(1,diffDays(parseDate(cs), parseDate(ce))+1); const prev=previewMap[project.id]; const po=prev?diffDays(range.start, parseDate(prev.nextStartDate)):null; const pw=prev?Math.max(1,diffDays(parseDate(prev.nextStartDate), parseDate(prev.nextEndDate))+1):null; return <div key={project.id} className="grid border-b border-[#1F1F24]" style={{gridTemplateColumns:`260px repeat(${totalDays}, minmax(28px,1fr))`}}><div className="border-r border-[#26262A] bg-[#111114] px-4 py-4"><div className="font-medium">{project.name}</div><div className="mt-1 text-xs text-[#9CA3AF]">{companyMap[project.companyId]}</div><div className="mt-1 text-[11px] text-[#6B7280]">{cs} → {ce}</div>{prev?<div className="mt-2 inline-block rounded-md bg-fuchsia-900/40 px-2 py-1 text-[10px] text-fuchsia-300">Preview thay đổi</div>:null}</div><div className="relative col-span-full" style={{gridColumn:`2 / span ${totalDays}`}}><div className="absolute inset-0 grid" style={{gridTemplateColumns:`repeat(${totalDays}, minmax(28px,1fr))`}}>{days.map(day=><div key={`${project.id}-${day.toISOString()}`} className="border-r border-[#17171A]" />)}</div><div className="relative h-20">{prev&&po!==null&&pw!==null?<div className="absolute top-4 z-10 flex h-12 items-center rounded-2xl border-2 border-dashed border-fuchsia-400 bg-fuchsia-950/30 px-3 text-xs font-medium text-fuchsia-300" style={{left:`calc(${(po/totalDays)*100}% + 4px)`, width:`calc(${(pw/totalDays)*100}% - 8px)`}}>Preview mới</div>:null}<button onPointerDown={(e)=>setDragging({projectId:project.id,startX:e.clientX,startDate:cs,endDate:ce})} className={`absolute top-4 h-12 rounded-2xl border bg-gradient-to-r px-3 text-sm font-medium text-white shadow-[0_0_16px_rgba(227,29,26,0.20)] ${priorityClass(project.priority)}`} style={{left:`calc(${(off/totalDays)*100}% + 4px)`, width:`calc(${(width/totalDays)*100}% - 8px)`}}>{project.name}</button></div></div></div>})}</div></div></div>
}

export default function ProjectOSApp() {
  const [page,setPage]=useState('dashboard');
  const [loading,setLoading]=useState(false); const [error,setError]=useState(null);
  const [companies,setCompanies]=useState([]); const [projects,setProjects]=useState([]); const [engagements,setEngagements]=useState([]); const [payments,setPayments]=useState([]); const [dashboard,setDashboard]=useState(null); const [timeline,setTimeline]=useState(null);
  const [pendingActions,setPendingActions]=useState([]); const [assistantMessages,setAssistantMessages]=useState([]); const [assistantInput,setAssistantInput]=useState('');
  const [backupTargets,setBackupTargets]=useState([]); const [backupPolicies,setBackupPolicies]=useState([]); const [backupRuns,setBackupRuns]=useState([]);
  const [selectedBackupTargetId,setSelectedBackupTargetId]=useState(''); const [backupTargetName,setBackupTargetName]=useState('Ổ local mặc định'); const [backupTargetPath,setBackupTargetPath]=useState('D:/ProjectVault/Backups'); const [backupTargetType,setBackupTargetType]=useState('local'); const [backupMode,setBackupMode]=useState('weekly'); const [backupLabel,setBackupLabel]=useState(''); const [keepLastN,setKeepLastN]=useState(12);
  const [companyForm,setCompanyForm]=useState({ companyName:'', legalName:'', companyType:'company', countryCode:'VN', defaultCurrency:'VND', paymentTermsDays:30 });
  const nav=[['dashboard','Dashboard'],['gantt','Gantt'],['projects','Projects'],['assistant','AI Assistant'],['backup','Backup'],['settings','Settings']];

  async function loadAll(){ setLoading(true); setError(null); try { const now=new Date(); const y=now.getFullYear(); const m=now.getMonth()+1; const startDate=new Date(y,m-1,1).toISOString(); const endDate=new Date(y,m,0).toISOString(); const [co,pr,en,da,ti,bt,bp,br]=await Promise.all([api('/api/companies').catch(()=>[]),api('/api/projects').catch(()=>[]),api('/api/engagements').catch(()=>[]),api(`/api/dashboard/unified?year=${y}&month=${m}`).catch(()=>null),api(`/api/timeline/overview?startDate=${encodeURIComponent(startDate)}&endDate=${encodeURIComponent(endDate)}`).catch(()=>null),api('/api/backups/targets').catch(()=>[]),api('/api/backups/policies').catch(()=>[]),api('/api/backups/runs').catch(()=>[])]); setCompanies(co||[]); setProjects((pr||[]).map(p=>({...p,startDate:onlyDate(p.startDate),endDate:onlyDate(p.endDate)||null}))); setEngagements((en||[]).map(e=>({...e,startDate:onlyDate(e.startDate),endDate:onlyDate(e.endDate)||null}))); setDashboard(da||null); setTimeline(ti||null); setBackupTargets(bt||[]); setBackupPolicies(bp||[]); setBackupRuns(br||[]); const defaultTarget=(bt||[])[0]; if(defaultTarget){ setSelectedBackupTargetId(defaultTarget.id); setBackupTargetName(defaultTarget.targetName); setBackupTargetPath(defaultTarget.rootPath); setBackupTargetType(defaultTarget.targetType); } const nextPayments=[]; if(da?.details?.projectPayments) nextPayments.push(...da.details.projectPayments.map(p=>({...p, sourceType:'project', sourceId:p.sourceId||p.projectId, date:onlyDate(p.date||p.paymentDate)}))); if(da?.details?.engagementPayments) nextPayments.push(...da.details.engagementPayments.map(p=>({...p, sourceType:'engagement', sourceId:p.sourceId||p.engagementId, date:onlyDate(p.date||p.paymentDate)}))); setPayments(nextPayments); } catch(e){ setError(e.message||'Không tải được dữ liệu'); } finally { setLoading(false);} }
  useEffect(()=>{ loadAll(); },[]);

  function buildAIContext(){ return { projects: projects.map(p=>({id:p.id,name:p.name,startDate:p.startDate,endDate:p.endDate,priority:p.priority})), overloadDays:(timeline?.dailySeries||[]).filter(d=>d.status==='critical'||d.status==='warning'), payments: payments.slice(-10), today: onlyDate(new Date().toISOString()) }; }
  async function runAssistant(message){ const input=(message||assistantInput).trim(); if(!input) return; setAssistantMessages(prev=>[...prev,{role:'user',content:input}]); setAssistantInput(''); try { const res=await api('/api/ai/assistant',{method:'POST', body: JSON.stringify({message:input, context:buildAIContext()})}); setAssistantMessages(prev=>[...prev,{role:'ai',content:res.reply}]); setPendingActions(res.actions||[]); } catch { setAssistantMessages(prev=>[...prev,{role:'ai',content:'AI chưa nối backend hoặc đang lỗi.'}]); } }
  async function confirmPendingActions(){ for(const action of pendingActions){ if(action.type==='reschedule_project'){ await rescheduleProjectDirect(action.projectId, action.nextStartDate, action.nextEndDate);} } setPendingActions([]); }
  async function rescheduleProjectDirect(projectId,nextStart,nextEnd){ const prev=projects; setProjects(list=>list.map(p=>p.id===projectId?{...p,startDate:nextStart,endDate:nextEnd}:p)); try { await api(`/api/projects/${projectId}`, {method:'PATCH', body:JSON.stringify({startDate:nextStart,endDate:nextEnd})}); await loadAll(); } catch(e){ setProjects(prev); setError(e.message||'Không cập nhật được lịch dự án'); } }
  async function createCompany(){ try{ setLoading(true); await api('/api/companies',{method:'POST', body:JSON.stringify(companyForm)}); setCompanyForm({ companyName:'', legalName:'', companyType:'company', countryCode:'VN', defaultCurrency:'VND', paymentTermsDays:30 }); await loadAll(); setPage('projects'); } catch(e){ setError(e.message||'Không tạo được công ty'); } finally{ setLoading(false);} }
  async function runAutoScheduling(){ try{ setLoading(true); const now=new Date(); const startDate=new Date(now.getFullYear(),now.getMonth(),1).toISOString(); const endDate=new Date(now.getFullYear(),now.getMonth()+1,0).toISOString(); const res=await api('/api/timeline/auto-scheduling',{method:'POST', body:JSON.stringify({startDate,endDate,dailyThreshold:85})}); setPendingActions((res.suggestions||[]).map(s=>({type:'reschedule_project', projectId:s.projectId, nextStartDate:s.suggestedStartDate, nextEndDate:s.suggestedEndDate}))); setPage('gantt'); } catch(e){ setError(e.message||'Không tạo được đề xuất'); } finally{ setLoading(false);} }
  async function createBackupTarget(){ try{ setLoading(true); await api('/api/backups/targets',{method:'POST', body:JSON.stringify({targetName:backupTargetName,targetType:backupTargetType,rootPath:backupTargetPath,isDefault:backupTargets.length===0,isEnabled:true})}); await loadAll(); } catch(e){ setError(e.message||'Không tạo được backup target'); } finally{ setLoading(false);} }
  async function saveBackupPolicy(){ try{ setLoading(true); await api('/api/backups/policies',{method:'POST', body:JSON.stringify({backupTargetId:selectedBackupTargetId,policyName:`Backup ${backupMode}`,frequency:backupMode,keepLastN,includeDocuments:true,includeFeedbackImages:true,isEnabled:true})}); await loadAll(); } catch(e){ setError(e.message||'Không lưu được policy'); } finally{ setLoading(false);} }
  async function runBackupNow(){ try{ setLoading(true); await api('/api/backups/run',{method:'POST', body:JSON.stringify({backupTargetId:selectedBackupTargetId,backupLabel,runType:'manual'})}); setBackupLabel(''); await loadAll(); } catch(e){ setError(e.message||'Không chạy được backup'); } finally{ setLoading(false);} }

  const summary=dashboard?.summary||{totalProjectGross:0,totalEngagementGross:0,totalWithheldTax:0,totalNetReceived:0};

  return <div className="flex h-screen bg-[#0D0D0F] text-[#F5F5F5]"><aside className="flex w-64 flex-col border-r border-[#26262A] bg-[#111114] p-4"><div className="mb-6 flex items-center gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#E31D1A] font-bold">DB</div><div><div className="font-semibold">ProjectOS</div><div className="text-xs text-[#9CA3AF]">DB9 Studio</div></div></div><div className="space-y-2">{nav.map(([key,label])=><button key={key} onClick={()=>setPage(key)} className={`w-full rounded-xl px-4 py-2 text-left transition ${page===key?'border border-[#2A2A30] bg-[#1A1A1D]':'hover:bg-[#1A1A1D]'}`}>{label}</button>)}</div><div className="mt-4"><Btn secondary onClick={loadAll} disabled={loading}>Refresh</Btn></div></aside><main className="flex-1 overflow-auto p-6">{error?<div className="mb-4 rounded-xl border border-[#5B1C1C] bg-[#2A1111] p-3 text-sm text-[#FFB4B4]">{error}</div>:null}{loading?<div className="mb-4 rounded-xl border border-[#26262A] bg-[#151518] p-3 text-sm text-[#D4D4D8]">Đang tải dữ liệu...</div>:null}
  {page==='dashboard' && <div className="space-y-6"><div><div className="text-2xl font-semibold">Dashboard</div><div className="text-sm text-[#9CA3AF]">ProjectOS overview</div></div><div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4"><Card><div className="text-sm text-[#9CA3AF]">Thu nhập dự án</div><div className="mt-2 text-2xl font-semibold">{formatMoney(summary.totalProjectGross)}</div></Card><Card><div className="text-sm text-[#9CA3AF]">Thu nhập part-time</div><div className="mt-2 text-2xl font-semibold">{formatMoney(summary.totalEngagementGross)}</div></Card><Card><div className="text-sm text-[#9CA3AF]">Thuế khấu trừ</div><div className="mt-2 text-2xl font-semibold">{formatMoney(summary.totalWithheldTax)}</div></Card><Card><div className="text-sm text-[#9CA3AF]">Thực nhận</div><div className="mt-2 text-2xl font-semibold">{formatMoney(summary.totalNetReceived)}</div></Card></div><Card><div className="mb-3 text-sm text-[#9CA3AF]">Cảnh báo nhanh</div><div className="space-y-2 text-sm text-[#D4D4D8]"><div>• Projects: {projects.length}</div><div>• Engagements: {engagements.length}</div><div>• Payments: {payments.length}</div></div><div className="mt-4 flex gap-2"><Btn onClick={runAutoScheduling}>Tạo đề xuất tự sắp lịch</Btn><Btn secondary onClick={()=>runAssistant('Hôm nay tao cần làm gì?')}>Gợi ý hôm nay</Btn></div></Card></div>}
  {page==='gantt' && <div className="space-y-6"><div><div className="text-2xl font-semibold">Gantt Timeline</div><div className="text-sm text-[#9CA3AF]">Drag, preview, confirm, apply</div></div><Card><div className="mb-4 flex items-center justify-between"><div className="text-sm text-[#9CA3AF]">Timeline trực tiếp</div><Btn onClick={runAutoScheduling}>Auto Scheduling</Btn></div><GanttChart projects={projects} companies={companies} previewActions={pendingActions} onDropReschedule={rescheduleProjectDirect} /></Card>{pendingActions.length>0?<Card><div className="mb-3 text-sm text-fuchsia-300">Đang preview {pendingActions.length} thay đổi trên Gantt</div><div className="flex gap-2"><Btn onClick={confirmPendingActions}>Confirm apply</Btn><Btn secondary onClick={()=>setPendingActions([])}>Huỷ</Btn></div></Card>:null}{timeline?.conflicts?.length?<Card><div className="mb-3 text-sm text-[#9CA3AF]">Conflicts</div><div className="space-y-2">{timeline.conflicts.map((c,idx)=><div key={idx} className="rounded-xl border border-[#26262A] bg-[#101013] p-3"><div className="font-medium">{c.summary}</div><div className="mt-1 text-sm text-[#9CA3AF]">{c.details}</div></div>)}</div></Card>:null}</div>}
  {page==='projects' && <div className="space-y-6"><div><div className="text-2xl font-semibold">Projects + Company</div><div className="text-sm text-[#9CA3AF]">Real API + Prisma</div></div><Card><div className="mb-4 text-sm text-[#9CA3AF]">Tạo công ty mới</div><div className="grid grid-cols-1 gap-4 md:grid-cols-2"><input className="rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" placeholder="Tên công ty" value={companyForm.companyName} onChange={e=>setCompanyForm(f=>({...f,companyName:e.target.value}))}/><input className="rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" placeholder="Tên pháp lý" value={companyForm.legalName} onChange={e=>setCompanyForm(f=>({...f,legalName:e.target.value}))}/><input className="rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" placeholder="Loại công ty" value={companyForm.companyType} onChange={e=>setCompanyForm(f=>({...f,companyType:e.target.value}))}/><input className="rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" placeholder="Quốc gia" value={companyForm.countryCode} onChange={e=>setCompanyForm(f=>({...f,countryCode:e.target.value}))}/></div><div className="mt-4"><Btn onClick={createCompany}>Lưu công ty</Btn></div></Card><Card><div className="mb-4 text-sm text-[#9CA3AF]">Danh sách dự án</div><div className="space-y-3">{projects.length===0?<div className="text-sm text-[#9CA3AF]">Chưa có dự án.</div>:projects.map(p=><div key={p.id} className="rounded-xl border border-[#26262A] bg-[#101013] p-4"><div className="font-medium">{p.name}</div><div className="mt-1 text-xs text-[#9CA3AF]">{onlyDate(p.startDate)} → {onlyDate(p.endDate)}</div><div className="mt-2 text-sm text-[#D4D4D8]">{formatMoney(p.contractValue)}</div></div>)}</div></Card></div>}
  {page==='assistant' && <div className="space-y-6"><div><div className="text-2xl font-semibold">AI Assistant</div><div className="text-sm text-[#9CA3AF]">Context-aware advisor</div></div><Card><div className="mb-4 h-[420px] space-y-2 overflow-auto rounded-xl border border-[#26262A] bg-[#101013] p-3">{assistantMessages.length===0?<div className="text-sm text-[#9CA3AF]">Hỏi về deadline, overload, payment, backup...</div>:assistantMessages.map((m,i)=><div key={i} className={`max-w-[70%] rounded-xl p-3 text-sm ${m.role==='user'?'ml-auto bg-[#E31D1A] text-white':'border border-[#26262A] bg-[#1A1A1D] text-[#F5F5F5]'}`}>{m.content}</div>)}</div><div className="flex gap-2"><input className="flex-1 rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" value={assistantInput} onChange={e=>setAssistantInput(e.target.value)} placeholder="Hỏi về deadline, tiền, overload..." /><Btn onClick={()=>runAssistant()}>Gửi</Btn><Btn secondary onClick={()=>runAssistant('Tự động tối ưu lại toàn bộ timeline cho tao')}>Auto reschedule ALL</Btn></div></Card></div>}
  {page==='backup' && <div className="space-y-6"><div><div className="text-2xl font-semibold">Backup</div><div className="text-sm text-[#9CA3AF]">Local + Cloud backup targets</div></div><div className="grid grid-cols-1 gap-6 xl:grid-cols-2"><Card><div className="mb-4 text-sm text-[#9CA3AF]">Tạo nơi lưu backup</div><div className="space-y-3"><input className="w-full rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" value={backupTargetName} onChange={e=>setBackupTargetName(e.target.value)} placeholder="Tên nơi lưu"/><select className="w-full rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" value={backupTargetType} onChange={e=>setBackupTargetType(e.target.value)}><option value="local">Local disk</option><option value="cloud_sync_folder">Cloud sync folder</option></select><input className="w-full rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" value={backupTargetPath} onChange={e=>setBackupTargetPath(e.target.value)} placeholder="Đường dẫn lưu"/><Btn onClick={createBackupTarget}>Tạo target</Btn></div></Card><Card><div className="mb-4 text-sm text-[#9CA3AF]">Policy + Run</div><div className="space-y-3"><select className="w-full rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" value={selectedBackupTargetId} onChange={e=>setSelectedBackupTargetId(e.target.value)}><option value="">Chọn target</option>{backupTargets.map(t=><option key={t.id} value={t.id}>{t.targetName}</option>)}</select><select className="w-full rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" value={backupMode} onChange={e=>setBackupMode(e.target.value)}><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select><input className="w-full rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" type="number" value={keepLastN} onChange={e=>setKeepLastN(Number(e.target.value))} placeholder="Keep last N"/><div className="flex gap-2"><Btn onClick={saveBackupPolicy}>Lưu policy</Btn><Btn secondary onClick={runBackupNow}>Run backup</Btn></div><input className="w-full rounded-xl border border-[#26262A] bg-[#101013] px-3 py-2 text-[#F5F5F5]" value={backupLabel} onChange={e=>setBackupLabel(e.target.value)} placeholder="Ghi chú backup"/></div></Card></div><Card><div className="mb-4 text-sm text-[#9CA3AF]">Lịch sử backup</div><div className="space-y-3">{backupRuns.length===0?<div className="text-sm text-[#9CA3AF]">Chưa có backup run.</div>:backupRuns.map(run=><div key={run.id} className="rounded-xl border border-[#26262A] bg-[#101013] p-3"><div className="font-medium">{run.backupLabel||'Backup run'}</div><div className="mt-1 text-xs text-[#9CA3AF]">{run.runType} · {run.status}</div><div className="mt-1 text-xs text-[#6B7280]">{run.archivePath||'No archive path'}</div></div>)}</div></Card></div>}
  {page==='settings' && <div className="space-y-6"><div><div className="text-2xl font-semibold">Settings</div><div className="text-sm text-[#9CA3AF]">Desktop behavior</div></div><Card><div className="space-y-3 text-sm text-[#D4D4D8]"><div>• Launch on Windows startup</div><div>• Start minimized to tray</div><div>• Reminder on boot</div><div className="text-[#9CA3AF]">Phần startup/tray cần lớp desktop Electron/Tauri bên ngoài UI này.</div></div></Card></div>}
  </main></div>;
}
